version: "3.7"
services:
  api:
    container_name: picts-manager-api
    build:
      context: .
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - ./uploads:/app/uploads
  database:
    image: bitnami/couchdb:3
    container_name: picts-manager-database
    environment:
      - COUCHDB_PASSWORD=couchdb
    ports:
      - '5984:5984'
      - '4369:4369'
      - '9100:9100'
    volumes:
      - picts-manager-database:/bitnami/couchdb

volumes:
  picts-manager-database:
